services:
  db:
    image: postgres:17
    container_name: estevao_db
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_HOST: ${DB_HOST:-localhost}
    volumes:
      - /var/lib/postgresql/data
