name: Continuous Integration

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
    types: [opened, synchronize]

jobs:
  style:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}

    strategy:
      matrix:
        otp: [25.x]
        elixir: [1.14.x]

    services:
      db:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOSTNAME: 0.0.0.0

    steps:
      - name: ☁️ Checkout repository
        uses: actions/checkout@v3

      - name: 💧 Setup Elixir ${{ matrix.elixir }} (OTP ${{matrix.otp}})
        uses: marmelasoft/elixir-setup@main
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
          build-flags: --all-warnings --warnings-as-errors

      - name: 🔬 Run the tests
        run: mix test --warnings-as-errors

      - name: 📏 Check code formating
        run: mix format --check-formatted
        if: always()

      - name: 🔍 Lint the code
        run: mix credo --strict --all
        if: always()
