name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
    types: [opened, synchronize]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-22.04]

    name: OTP / Elixir (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    env:
      MIX_ENV: test

    steps:
      - name: ☁️ Checkout repository
        uses: actions/checkout@v6

      - name: 💧 Setup Elixir
        uses: marmelasoft/elixir-setup@main
        with:
          version-file: .tool-versions
          version-type: strict
          cache-plts: true

      - name: 🔬 Run the tests
        run: mix test --all-warnings --warnings-as-errors

      - name: 🔍 Analyze the code
        run: mix dialyzer --format github

      - name: 🧹 Check code formating
        run: mix format --check-formatted
        if: always()

      - name: 💡 Lint the code
        run: mix credo --strict --all
        if: always()

      - name: 🛡️ Search vulnerabilities
        run: |
          mix hex.audit
          mix deps.audit
          mix sobelow --threshold low --ignore Config.HTTPS
        if: always()

      - name: ♻️ Check unused dependencies
        run: mix deps.unlock --check-unused
